export enum Mensaje {
    REGISTRO_ESTUDIANTES_EXITOSO = 'Estudiantes cargados exitosamente',
    ERROR_CARGAR_ESTUDIANTES = 'Carga de estudiantes fallida. Verifica los datos e intenta nuevamente',
    REGISTRE_CAMPOS_OBLIGATORIOS = 'Completa los campos marcados como obligatorios (*)',
    ESTUDIANTE_ELIMINADO_CORRECTAMENTE = 'Estudiante eliminado correctamente',
    SOLICITUD_ELIMINADA_CORRECTAMENTE = 'Solicitud eliminada correctamente',
    CURSO_ELIMINADO_CORRECTAMENTE = 'Curso eliminado correctamente',
    EMPRESA_ELIMINADA_CORRECTAMENTE = 'Empresa eliminada correctamente',
    CONFIRMAR_ELIMINAR_ESTUDIANTE = '¿Está seguro de eliminar este estudiante?',
    CONFIRMAR_ELIMINAR_REGISTRO = '¿Está seguro de eliminar este registro?',
    CONFIRMAR_SALIR_SIN_GUARDAR = 'La información no ha sido guardada, ¿Desea salir?',
    REGISTRO_DOCENTES_EXITOSO = 'Docentes cargados exitosamente',
    ERROR_CARGAR_DOCENTESS = 'Carga de docentes fallida. Verifica los datos e intenta nuevamente',
    DOCENTE_ELIMINADO_CORRECTAMENTE = 'Docente eliminado correctamente',
    CONFIRMAR_ELIMINAR_DOCENTE = '¿Está seguro de eliminar este docente?',
    ACTUALIZACION_EXITOSA = 'El registro fue actualizado exitosamente',
    GUARDADO_EXITOSO = 'Los datos han sido guardados exitosamente',
}
