import {
    DatosSolicitudCancelacionAsignatura,
    InfoAsingAdicionCancelacion,
    DatosSolicitudAplazamiento,
    DatosSolHomologPostSave,
    DatosSolicitudCursarAsignatura,
    DatosSolicitudAvalPasantia,
    DatosApoyoPasantia,
    DatosReconoCreditos,
    DatosApoyoCongreso,
    DatosApoyoPublicacion,
    DatosActividadPracticaDocente,
    DatosAvalPracticaDocente,
    DatosSolicitudBecaDescuento,
} from '../indiceModelos';

export class SolicitudSave {
    static nuevoSolicitudSave(obj: Object) {
        return new SolicitudSave(
            obj['idTipoSolicitud'],
            obj['idEstudiante'],
            obj['idTutor'],
            obj['datosHomologacion'],
            obj['datosAdicionAsignatura'],
            obj['datosCancelarAsignatura'],
            obj['datosAplazarSemestre'],
            obj['datosCursarAsignatura'],
            obj['datoAvalPasantiaInv'],
            obj['datosApoyoEconomico'],
            obj['datosRecCreditosPasantia'],
            obj['datosAvalSeminario'],
            obj['datosApoyoEconomicoCongreso'],
            obj['datosApoyoEconomicoPublicacion'],
            obj['datosActividadDocenteRequest'],
            obj['datosAvalComite'],
            obj['datoSolicitudBeca'],
            obj['requiereFirmaDirector'],
            obj['idDirector'],
            obj['firmaEstudiante'],
            obj['numPaginaTutor'],
            obj['numPaginaDirector'],
            obj['posXTutor'],
            obj['posYTutor'],
            obj['posXDirector'],
            obj['posYDirector'],
            obj['oficioPdf']
        );
    }

    constructor(
        public idTipoSolicitud: number,
        public idEstudiante: string,
        public idTutor: string,
        public datosHomologacion: DatosSolHomologPostSave,
        public datosAdicionAsignatura: InfoAsingAdicionCancelacion[],
        public datosCancelarAsignatura: DatosSolicitudCancelacionAsignatura,
        public datosAplazarSemestre: DatosSolicitudAplazamiento,
        public datosCursarAsignatura: DatosSolicitudCursarAsignatura,
        public datosAvalPasantiaInv: DatosSolicitudAvalPasantia,
        public datosApoyoEconomico: DatosApoyoPasantia,
        public datosReconocimientoCreditos: DatosReconoCreditos,
        public datosAvalSeminario: any,
        public datosApoyoEconomicoCongreso: DatosApoyoCongreso,
        public datosApoyoEconomicoPublicacion: DatosApoyoPublicacion,
        public datosActividadDocenteRequest: DatosActividadPracticaDocente[],
        public datosAvalComite: DatosAvalPracticaDocente[],
        public datosSolicitudBeca: DatosSolicitudBecaDescuento,
        public requiereFirmaDirector: boolean,
        public idDirector: string,
        public firmaEstudiante: boolean,
        public numPaginaTutor: number,
        public numPaginaDirector: number,
        public posXTutor: number,
        public posYTutor: number,
        public posXDirector: number,
        public posYDirector: number,
        public oficioPdf: string
    ) {}
}
